steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fras-frontend:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/fras-frontend:latest', './frontend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fras-frontend:$SHORT_SHA']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fras-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fras-frontend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--cpu'
      - '1'
      - '--memory'
      - '1Gi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '4'
      - '--concurrency'
      - '80'
images:
  - 'gcr.io/$PROJECT_ID/fras-frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/fras-frontend:latest'
options:
  logging: 'CLOUD_LOGGING_ONLY'