steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fras-backend:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/fras-backend:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fras-backend:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fras-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fras-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--cpu'
      - '2'
      - '--memory'
      - '4Gi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '6'
      - '--concurrency'
      - '5'
      - '--timeout'
      - '60s'
images:
  - 'gcr.io/$PROJECT_ID/fras-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/fras-backend:latest'
options:
  machineType: 'N1_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'
